#pragma once

#include <string>

namespace ros2_julia
{

// Proof-of-concept message wrapper for std_msgs/msg/String.
//
// This is intentionally minimal: it owns the underlying ROS2 C message memory
// (generated by rosidl_generator_c) and exposes a `void*` for rcl_publish/rcl_take.
class StdMsgsString
{
public:
  StdMsgsString();
  explicit StdMsgsString(const std::string& data);
  ~StdMsgsString();

  StdMsgsString(const StdMsgsString&) = delete;
  StdMsgsString& operator=(const StdMsgsString&) = delete;

  StdMsgsString(StdMsgsString&&) = delete;
  StdMsgsString& operator=(StdMsgsString&&) = delete;

  void set_data(const std::string& data);
  std::string get_data() const;

  void* ros_message();
  const void* ros_message() const;

private:
  struct Impl;
  Impl* impl_ = nullptr;
};

// Returns message type support for `std_msgs/msg/String` if available at build time.
//
// We return `const void*` so CxxWrap can treat it as `Ptr{Cvoid}` without needing
// a factory for `rosidl_message_type_support_t`.
const void* typesupport_std_msgs_string();

}  // namespace ros2_julia
